---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: PLACEHOLDER_NAME
  labels:
    app: PLACEHOLDER_APP
    model-type: "PLACEHOLDER_MODEL_TYPE"
    deployment-tag: "PLACEHOLDER_TAG"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PLACEHOLDER_APP
  template:
    metadata:
      labels:
        app: PLACEHOLDER_APP
        model-type: "PLACEHOLDER_MODEL_TYPE"
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: sagemaker.amazonaws.com/compute-type
                operator: In
                values: ["hyperpod"]
          - weight: 90
            preference:
              matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: Exists
          - weight: 80
            preference:
              matchExpressions:
              - key: karpenter.sh/capacity-type
                operator: Exists
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values: ["ml.g6.12xlarge"]
      containers:
        - name: SERVENGINE
          image: DOCKER_IMAGE
          resources:
            requests:
              nvidia.com/gpu: 1
            limits:
              nvidia.com/gpu: 1
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: persistent-storage-s3
              mountPath: /s3
              readOnly: true
            - name: local-cache
              mountPath: /root/.cache
            - name: shm
              mountPath: /dev/shm
          env:
            - name: HF_HOME
              value: "/root/.cache/huggingface"
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
      volumes:
        - name: persistent-storage-s3
          persistentVolumeClaim:
            claimName: s3-claim
        - name: local-cache
          hostPath:
            path: /opt/dlami/nvme/.cache
            type: DirectoryOrCreate
        - name: shm
          emptyDir:
            medium: Memory
            # sizeLimit: 2Gi
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"