apiVersion: sagemaker.amazonaws.com/v1
kind: HyperPodPyTorchJob
metadata:
  labels:
    app.kubernetes.io/name: HyperPod
    app.kubernetes.io/managed-by: kustomize
    app: hz-torchrecipe-1
  name: hz-torchrecipe-1
spec:
  nprocPerNode: "4"
  replicaSpecs:
    - name: pods
      replicas: 1
      template:
        spec:
          # serviceAccountName: mlflow-service-account
          # serviceAccountName: hp-training-operator-pod-manager
          serviceAccountName: mlflow-service-account
          nodeSelector:
            beta.kubernetes.io/instance-type: ml.g6e.12xlarge
          containers:
            - name: pytorch
              image: 633205212955.dkr.ecr.us-west-2.amazonaws.com/hyperpod-instantstart-torchtitan:latest
              imagePullPolicy: Always
              ports:
                - containerPort: 8080 # HyperPodElasticAgent port
              resources:
                requests:
                  nvidia.com/gpu: 4
                  vpc.amazonaws.com/efa: 0
                limits:
                  nvidia.com/gpu: 4
                  vpc.amazonaws.com/efa: 0
              env:
              - name: LOGLEVEL
                value: "INFO"
              - name: FI_PROVIDER
                value: "efa"
              # - name: TORCH_DISTRIBUTED_DEBUG
              #   value: "DETAIL"
              # - name: TORCH_NCCL_ENABLE_MONITORING
              #   value: "1"
              # - name: TORCH_NCCL_TRACE_BUFFER_SIZE
              #   value: "20000"
              - name: NCCL_DEBUG
                value: "DEBUG"
              # - name: NCCL_SOCKET_IFNAME
              #   value: "^lo"
              - name: NCCL_SOCKET_IFNAME
                value: "eth0"
              # - name: TORCH_NCCL_ASYNC_ERROR_HANDLING
              #   value: "1"
              # - name: HF_TOKEN
              #   value: "12345"
              # - name: MLFLOW_TRACKING_URI
              #   value: arn:aws:sagemaker:us-west-2:633205212955:mlflow-tracking-server/pdx-mlflow
              # - name: MLFLOW_EXPERIMENT_NAME
              #   value: hz-torchrecipe-1
              # - name: MLFLOW_TAG_NPROCPERNODE
              #   value: "4"
              # - name: MLFLOW_TAG_REPLICAS
              #   value: "1"
              # - name: MLFLOW_TAG_EFAPERNODE
              #   value: "1"
              # - name: MLFLOW_TAG_INSTANCETYPE
              #   value: ml.g6.12xlarge
              - name: TT_RECIPE_CONF_PATH
                value: /s3/train-recipes/torchtitan/qwen3_1.7b.toml
              - name: TT_RECIPE_PARAMS
                value: --metrics.log_freq=1 --training.steps=50 --training.local_batch_size=1 --parallelism.tensor_parallel_degree=1 --model.hf_assets_path="./assets/hf/Qwen3-1-7B"
              command: ["bash", "/s3/train-recipes/torchtitan/torchtitan_recipe_dist_run.sh"]
              volumeMounts:
                - name: persistent-storage-s3
                  mountPath: /s3
                  readOnly: false
                - name: shmem
                  mountPath: /dev/shm
                - name: local
                  mountPath: /local
                - name: inst-nvme
                  mountPath: /ckpt-path
                - name: local-cache
                  mountPath: /root/.cache
                # - name: persistent-storage
                #   mountPath: /dfsx
          volumes:
            - name: shmem
              hostPath: 
                path: /dev/shm
            - name: local
              hostPath:
                path: /mnt/k8s-disks/0
            - name: local-cache
              hostPath:
                path: /opt/dlami/nvme/.cache
            - name: inst-nvme
              hostPath:
                path: /opt/dlami/nvme/checkpoints/
            # - name: persistent-storage
            #   persistentVolumeClaim:
            #     claimName: fsx-claim
            - name: persistent-storage-s3
              persistentVolumeClaim:
                claimName: s3-claim
  runPolicy:
    jobMaxRetryCount: 5
    restartPolicy:
      numRestartBeforeFullJobRestart: 3
      evalPeriodSeconds: 21600
      maxFullJobRestarts: 1
    cleanPodPolicy: "All"
